# SuperAgent Configuration

agent:
  id: ""
  location: "default"
  server_id: ""
  work_dir: "/var/lib/superagent"
  data_dir: "/var/lib/superagent/data"
  temp_dir: "/tmp/superagent"
  pid_file: "/var/run/superagent.pid"
  user: "superagent"
  group: "superagent"
  max_concurrent_ops: 5
  heartbeat_interval: "30s"

backend:
  base_url: "http://localhost:9999/api"  # Set to a dummy local URL for standalone CLI
  api_token: "dummy-token"
  token_file: ""
  refresh_interval: "30s"
  timeout: "30s"
  retry_attempts: 3
  retry_delay: "5s"
  insecure_skip_tls: false
  webhook_endpoint: "/webhook"
  webhook_secret: "dummy-secret"

docker:
  host: "unix:///var/run/docker.sock"
  version: "1.41"
  network_name: "superagent"
  log_driver: "json-file"
  cleanup_interval: "1h"
  cleanup_retention: "24h"
  default_cpu_limit: "1"
  default_memory_limit: "1G"
  default_storage_limit: "10G"

git:
  ssh_key_path: ""
  timeout: "30s"
  max_depth: 50
  cache_dir: "/var/cache/superagent/git"
  cache_retention: "24h"

traefik:
  enabled: false
  provider: "file"
  config_file: "/etc/traefik/dynamic.yml"
  base_domain: "localhost"
  cert_resolver: "letsencrypt"
  enable_tls: false

security:
  encryption_key_file: "/etc/superagent/encryption.key"
  token_rotation_interval: "24h"
  audit_log_enabled: false
  audit_log_path: "/var/log/superagent/audit.log"
  run_as_non_root: true
  read_only_root_fs: true
  no_new_privileges: true

monitoring:
  enabled: false
  metrics_port: 9090
  metrics_path: "/metrics"
  health_check_port: 8080
  health_check_path: "/health"
  prometheus_enabled: false
  metrics_interval: "15s"

logging:
  level: "info"
  format: "json"
  output: "stdout"
  log_file: ""
  max_size: 100
  max_backups: 10
  max_age: 30
  compress: true

resources:
  cpu_quota: "80%"
  memory_quota: "80%"
  storage_quota: "80%"
  network_quota: "1Gbps"
  max_containers: 50
  max_volumes: 100
  max_networks: 10
  reserved_cpu: "0.5"
  reserved_memory: "1G"
  reserved_storage: "10G"

networking:
  allowed_ports: [80, 443, 8080, 8443]
  blocked_ports: [22, 23, 135, 139, 445]
  dns_servers: ["8.8.8.8", "8.8.4.4"]
  firewall_enabled: false